#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ] || [ -n "${HASHED_PASSWORD}" ]; then
  AUTH="password"
else
  AUTH="none"
  echo "starting with no password"
fi

if [ -z ${PROXY_DOMAIN+x} ]; then
  PROXY_DOMAIN_ARG=""
else
  PROXY_DOMAIN_ARG="--proxy-domain=${CODE_PROXY_DOMAIN}"
fi

exec /usr/bin/code-server \
		--bind-addr 0.0.0.0:8443 \
		--user-data-dir /home/jovyan/data \
		--extensions-dir /home/jovyan/extensions \
		--disable-telemetry \
		--auth "${AUTH}" \
		"${PROXY_DOMAIN_ARG}" \
		/home/jovyan/workspace
